#!/bin/bash
set -e

# Block writes to thoughts/searchable/ — it's auto-generated by `humanlayer thoughts sync`.
# Exit codes: 0=allow, 2=block

input=$(cat)

file_path=$(echo "$input" | jq -r '.tool_input.file_path // empty')

if [[ -n "$file_path" && "$file_path" == *"/thoughts/searchable/"* ]]; then
  # Extract the relative path after searchable/ to suggest the canonical path
  canonical=${file_path/\/thoughts\/searchable\//\/thoughts\/}
  echo "BLOCKED: thoughts/searchable/ is read-only (auto-generated by \`humanlayer thoughts sync\`)." >&2
  echo "Use the canonical path instead: $canonical" >&2
  exit 2
fi

exit 0
